name: Run Test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls -al
    - uses: actions/checkout@v3
    - run: ls -al
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package
  
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -al
          pwd
          abc
          ls -al