name: GitHub Actions Demo
run-name: Deploy 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SPRING_BOOT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Build & Test
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} '
            cd action-man &&
            git pull &&
            ./mvnw clean package &&     
            sudo cp target/action-man.jar /var/action-man/action-man.jar                                               
          '

      - name: Restart
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} 'sudo systemctl restart action-man'
          